### ISSUE TITLE
Wrap default attributes in `defaults` key

### ISSUE THREAD

**Issue by PikachuEXE** [brainspec/enumerize#120]
So that it looks like:

``` yaml
en:
  defaults:
    sex:
      male: Male
      female: Female
  user:
    some_preference:
      p1: blah
      p2: blahblah
```

This avoids conflicting keys with model names and attribute names, and makes the file clearer (unless some there is a model called `Defaults`)

Not urgent, just a suggestion for a backward incompatible version
I would just do the merging hash approach for now :)
