### ISSUE TITLE
"defaults" key not used anymore?

### ISSUE THREAD

**Issue by ldonnet** [brainspec/enumerize#173]
Hi,

I use your great gem for many projects but i encounter a bug in my rails application (  rails v 3.2.19 ).
When I use as in your documentation : 

``` yml
en:
  enumerize:
    defaults:
      sex:
        male: "Male"
        female: "Female"
```

It fails to load i18n resources. 

And the good syntax seems to be : 

``` yml
en:
  enumerize:
      sex:
        male: "Male"
        female: "Female"
```

Could you explain what the good way to write I18n?
