### ISSUE TITLE
I18n fallbacks and Enumerize translations does not work properly (+Simple form ?)

### ISSUE THREAD

**Issue by Erowlin** [brainspec/enumerize#261]
We've setup multiple fallback to support locale format like that : 'fr-FR', 'fr-UK', 'en-UK' etc...
Each locale map to a language-COUNTRY_CODE, the fallback is done using the [fallback feature](https://github.com/svenfuchs/i18n/wiki/Fallbacks) of I18n. 

So language mapping looks like this : 

```
- 'en-UK' => 'en'
- 'en-DE' => 'en'
- 'en-FR' => 'en'
- 'fr-UK' => 'fr'
- 'fr-DE' => 'fr'
- 'fr-FR' => 'fr'
- 'de-UK'  => 'de'
- 'de-DE' => 'de'
- de-FR' => 'de'
```

We've a model `EmailTemplate` that has a field `locale`. For now, we enumerize the field on those values using `enumerize :locale, in: %w(fr en)`. 

In enumerize.en.yml, we have a translation key that looks like this : 

```
enumerize:
    defaults:
      locale: &locale
        fr: 'French'
        en: 'English'
        de: 'German'
    locale:
      en: "English"
      fr: "French"
```

When generating an input with SimpleForm, the entries are not properly translated : 
The text displayed is 'fr' and 'en' instead of 'French' and 'English'. 

`current_user.locale` #=> `en-UK`
All other fields are properly translated (the one without enumerize). All the fields with Enumerize have this problem, this is not an isolated case. 

To fix the problem, we had to do `enumerize :locale, in: [:fr, :en], i18n_scope: 'enumerize.locale'` (Specify the i18n scope). 

Let me know if you need more informations. Thanks
