### ISSUE TITLE
Capitalization not preserved when using I18n

### ISSUE THREAD

**Issue by nhinze** [brainspec/enumerize#266]
I'm using the following I18n to have nice strings for my select box:

```
en:
  enumerize:
    clock:
      time_of_day:
        all_day: "All Day"
        am: "AM"
        pm: "PM"
```

However, when I output the text I get:

> All day
> Am
> Pm

instead of:

> All Day
> AM
> PM

using:

`<%= @clock.time_of_day.text %>`

Rails 4.2.7
Ruby 2.2.5
Enumerize 2.0.1
