### ISSUE TITLE
nested i18n_scope is not working

### ISSUE THREAD

**Issue by nhinze** [brainspec/enumerize#301]
I'm trying to use the nested i18n_scope, but it is not working on Rails 5.1.4:

```
class Questionnaires::Question < ApplicationRecord

  extend Enumerize
  extend ActiveModel::Naming
  enumerize :question_type,    in: {:short_text => 0, :long_text => 1, :numeric => 2}, i18n_scope: "question.question_type"

end
```

```
en:
  enumerize:
    question:
      question_type:
        short_text: "One line text answer"
        long_text: "Multiple lines text answer"
        numeric_text: "Numeric answer"
```

However, if I remove the nesting, it works:

```
class Questionnaires::Question < ApplicationRecord

  extend Enumerize
  extend ActiveModel::Naming
  enumerize :question_type,    in: {:short_text => 0, :long_text => 1, :numeric => 2}, i18n_scope: question_type"

end
```

```
en:
  enumerize:
    question_type:
      short_text: "One line text answer"
      long_text: "Multiple lines text answer"
      numeric_text: "Numeric answer"
```
