### ISSUE TITLE
I18n key for README file 

### ISSUE THREAD

**Issue by ldonnet** [brainspec/enumerize#454]
In README file localization is never with enumerize key : 

```
class Person
  extend Enumerize
  extend ActiveModel::Naming

  enumerize :status, in: %w[student employed retired], i18n_scope: "status"
  enumerize :roles, in: %w[user admin], i18n_scope: ["user.roles", "roles"]
  enumerize :color, in: %w[green blue], i18n_scope: proc { |value| "color" }
end

# localization file
en:
  status:
    student: "Student"
    employed: "Employed"
    retired: "Retiree"
  user:
    roles:
      user: "User"
  roles:
    admin: "Admin"
```

I think enumerize key should be added no?
```
# localization file
en:
  enumerize:
    status:
      student: "Student"
      employed: "Employed"
      retired: "Retiree"
    user:
      roles:
        user: "User"
    roles:
      admin: "Admin"
```
