### ISSUE TITLE
Unable to get text from multiple Enumeration

### ISSUE THREAD

**Issue by sslotnick** [brainspec/enumerize#83]
If I have a model that accepts a multiple enumeration, I am unable to get the text labels for the selected values.  For a non-multiple enumeration, I can access the method text which returns the display label.  Multiple enumerations return an array of the values as strings.

This seems like a gap in functionality for multiple enumerations, but maybe I'm just doing something incorrectly!  Thanks!

en.yml

```
en:
  enumerize:
    profile:
      languages:
        c_language: "C"
        c_plus_plus_language: "C++"
        java_language: "Java"
        ruby_language: "Ruby"
```

Profile

```
LANGUAGES = [ :c_language, :c_plus_plus_language, :java_language, :ruby_language] enumerize :languages, in: LANGUAGES, multiple: true
enumerize :one_language, in: LANGUAGES
```

Repro

```
## Set the enumeration ##
user.profile.languages = [:ruby_language, :java_language]
user.profile.one_language = :ruby_language

## Get the values ##
user.profile.one_language
# "ruby_language"

user.profile.languages
# [:ruby_language, :java_language]

user.profile.one_language.text
# "Ruby"

user.profile.languages.text
# NoMethodError: undefined method `text' for #<Array:0x007fe77e31ef30> ....
```
